name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: dependencies
      run: sudo apt-get install -y build-essential libboost-test-dev libboost-program-options-dev cmake zlib1g-dev libbz2-dev liblzma-dev libicu-dev uchardet libuchardet-dev libzip-dev wget
    - name: cmake
      run: |
        cmake -E make_directory build
        cd build
        cmake ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j2
    - name: Unit Tests
      working-directory: build
      run: ctest -j2
    # - name: Regression Tests
    #   working-directory: tests
    #   run: |
    #     ../build/bin/warc2text -v --json hello-world.warc.gz > hello-world.json
    #     shasum -c checksums.txt
